NumPy - Numerical Pythom

Advantages of Numpy Arrays:

1.   Allows several Mathematical Operations
2.   Faster operations



In [2]:
import numpy as np


List vs Numpy (Time taken)

In [2]:
from time import process_time

In [5]:
python_list = [i for i in range(100000)]

start_t = process_time();

python_list = [i+5 for i in range(100000)]

end_t = process_time();

print(end_t- start_t)

0.015168968000000227


In [7]:
np_array = np.array([i for i in range(100000)])

start_t = process_time();

np_array += 5

end_t = process_time();

print(end_t- start_t)

0.00047791200000002476


Numpy Array

In [8]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [9]:
nparray= np.array([1,2,3,4,5])
print(nparray)
type(nparray)

[1 2 3 4 5]


numpy.ndarray

In [10]:
nparray.shape

(5,)

In [12]:
a = np.array([(1,2,3,4),(5,4,3,2)])
a.shape

(2, 4)

In [14]:
a = np.array([(1,2,3,4),(5,4,3,2)],dtype=float)
print(a)

[[1. 2. 3. 4.]
 [5. 4. 3. 2.]]


Initial Placeholders in numpy array

In [5]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
z = np.full((5,4),5.0)

In [8]:
print(z)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [9]:
#Creating Identity Matrix
a =np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
#Random Value
b = np.random.random((2,3))
print(b)

[[0.29863017 0.01970503 0.00648898]
 [0.94887945 0.64082674 0.19662188]]


In [11]:
#Random Integers
b = np.random.randint(10,100,(2,3))
print(b)

[[47 78 10]
 [38 83 52]]


In [3]:
#Array of Evenly Spaced Values
d= np.linspace(10,40,5)
print(d)
#Starting Value, Ending Value, No. of Values assigned

[10.  17.5 25.  32.5 40. ]


In [5]:
#Array of Evenly Spaced Values (Specifying the Step)
e= np.arange(10,40,5)
print(e)

[10 15 20 25 30 35]


In [6]:
#Convert a list to a numpy array
list1=[10,20,30,35,45]
np_array=np.asarray(list1)
print(np_array)

[10 20 30 35 45]


Analysing a NumPy array

In [7]:
c = np.random.randint(10,40,(5,5))
print(c)

[[32 35 36 26 16]
 [23 21 35 18 37]
 [21 35 11 26 10]
 [13 31 30 39 25]
 [20 18 10 29 26]]


In [8]:
#Number of Dimensions
print(c.ndim)

2


In [9]:
#No. of elements
print(c.size)
#Data Type
print(c.dtype)

25
int64


Mathematical Operations on a NumPy Array

In [10]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [11]:
print(a)
print(b)
print(a-b)
print(a+b)
print(a*b)
print(a/b)

[[8 8 3]
 [5 2 5]
 [0 2 5]]
[[13 19 18]
 [13 12 18]
 [17 17 10]]
[[ -5 -11 -15]
 [ -8 -10 -13]
 [-17 -15  -5]]
[[21 27 21]
 [18 14 23]
 [17 19 15]]
[[104 152  54]
 [ 65  24  90]
 [  0  34  50]]
[[0.61538462 0.42105263 0.16666667]
 [0.38461538 0.16666667 0.27777778]
 [0.         0.11764706 0.5       ]]


Array Manipulation in Python

In [14]:
array = np.random.randint(3,40,(5,5))
print(array)
#transpose
array1= np.transpose(array)
print(array1)

[[34  7 20 39 24]
 [16 11  9 11 34]
 [24  4 18 29 37]
 [33 14 39 33 37]
 [34  7 18  7 17]]
[[34 16 24 33 34]
 [ 7 11  4 14  7]
 [20  9 18 39 18]
 [39 11 29 33  7]
 [24 34 37 37 17]]


In [18]:
array4 = np.random.randint(3,40,(5,2))
print(array4)
array3= array4.reshape(2,5)
print(array3)

[[27 23]
 [15 27]
 [36 30]
 [32 20]
 [10  3]]
[[27 23 15 27 36]
 [30 32 20 10  3]]
